# general settings
name: 001_train_ESRGAN_SwinIR_SRx4_P48W8_Carbonate_500k_B4G8
model_type: SwinIRModel
scale: 4
num_gpu: auto
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: Carbonates
    type: PairedImageDataset
    dataroot_gt: ./datasets/CARBONATES/High_sub/train/
    dataroot_lq: ./datasets/CARBONATES/Low_sub/train/
    meta_info_file: ./datasets/CARBONATES/meta_info/meta_info_high_carbon.txt
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Carbon10
    type: PairedImageDataset
    dataroot_gt: ./datasets/CARBONATES/High_sub/validation/
    dataroot_lq: ./datasets/CARBONATES/Low_sub/validation/
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR
  upscale: 4
  in_chans: 3
  img_size: 48
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 96
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 4
  upsampler: 'nearest+conv'
  resi_connection: '3conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [10000, 25000, 40000, 45000, 100000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: MSELoss
    loss_weight: !!float 0.05
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 0.2
    style_weight: 0.2
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 0.05
# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher
    niqe:
      type: calculate_niqe
      crop_border: 4
      test_y_channel: false
      better: higher


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: # medical_SwinIR
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
