name: poreboostgan_esrgan_x4_gray
model_type: ESRGANModel
scale: 4
num_gpu: auto
manual_seed: 0

datasets:
  train:
    name: carbonates_train
    type: PairedImageDataset
    dataroot_gt: data/mengyang/CARBONATES/3DSR/High_sub/train
    dataroot_lq: data/mengyang/CARBONATES/3DSR/Low_sub/train
    meta_info_file: data/mengyang/CARBONATES/3DSR/meta_info/meta_info_high_carbon.txt
    filename_tmpl: '{}'
    img_flag: grayscale
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: carbonates_val
    type: PairedImageDataset
    dataroot_gt: data/mengyang/CARBONATES/3DSR/High_sub/validation
    dataroot_lq: data/mengyang/CARBONATES/3DSR/Low_sub/validation
    img_flag: grayscale
    io_backend:
      type: disk

network_g:
  type: RRDBNet
  num_in_ch: 1
  num_out_ch: 1
  scale: 4
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 1
  num_feat: 64

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [10000, 25000, 40000, 45000, 300000]
    gamma: 0.5

  total_iter: 400000
  warmup_iter: -1

  pixel_opt:
    type: MSELoss
    loss_weight: !!float 0.01
    reduction: mean
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

val:
  val_freq: !!float 5e3
  save_img: true
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher
    niqe:
      type: calculate_niqe
      crop_border: 4
      test_y_channel: false
      better: higher

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
